{
 "title": "Modified Story Validator Watcher",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cosmos_validator_watcher_block_height,chain_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 } },
  {
   "title": "Active Set",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cosmos_validator_watcher_active_set{chain_id=\"$chain_id\"})"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cosmos_validator_watcher_block_height{chain_id=\"$chain_id\"})"
    }
   ]
  },
  {
   "title": "Total Staked",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validator_watcher_tokens{chain_id=\"$chain_id\"})"
    }
   ]
  },
  {
   "title": "Block / min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(cosmos_validator_watcher_block_height{chain_id=\"$chain_id\"}[10m])) by (chain_id) / 10"
    }
   ]
  },
  {
   "title": "Seat Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cosmos_validator_watcher_seat_price{chain_id=\"$chain_id\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Validators Stats",
   "type": "table",
   "gridPos": { "h": 37, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "100 * \nsum(rate(cosmos_validator_watcher_validated_blocks{chain_id=\"$chain_id\"}[5m])) by (name)\n/ on(instance) group_left()\nsum(rate(cosmos_validator_watcher_tracked_blocks{chain_id=\"$chain_id\"}[5m]))"
    },
    {
     "expr": "100 * \nsum(rate(cosmos_validator_watcher_solo_missed_blocks{chain_id=\"$chain_id\"}[5m])) by (name)\n/ on(instance) group_left()\nsum(rate(cosmos_validator_watcher_tracked_blocks{chain_id=\"$chain_id\"}[5m]))"
    },
    {
     "expr": "max(cosmos_validator_watcher_rank{cluster=\"$cluster\",namespace=\"$namespace\"}) by (name)"
    },
    {
     "expr": "max(cosmos_validator_watcher_tokens{chain_id=\"$chain_id\"}) by (name)"
    },
    {
     "expr": "max(cosmos_validator_watcher_is_bonded{chain_id=\"$chain_id\"}) by (name)"
    },
    {
     "expr": "max(cosmos_validator_watcher_is_jailed{chain_id=\"$chain_id\"}) by (name)"
    },
    { "expr": "cometbft_", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "100 * \nsum(rate(cosmos_validator_watcher_validated_blocks{chain_id=\"$chain_id\"}[5m])) by (name)\n/ on(instance) group_left()\nsum(rate(cosmos_validator_watcher_tracked_blocks{chain_id=\"$chain_id\"}[5m]))"
    }
   ]
  },
  {
   "title": "Missed Blocks (Solo)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "max(increase(cosmos_validator_watcher_solo_missed_blocks{chain_id=\"$chain_id\"}[30s])) by (name)"
    }
   ]
  },
  {
   "title": "Block / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "max(increase(cosmos_validator_watcher_block_height{chain_id=\"$chain_id\"}[10m])) by (chain_id) / 10"
    }
   ]
  }
 ]
}